"""empty message

Revision ID: 53ccc6e9e5d2
Revises: b7d3a1a34f34
Create Date: 2024-05-28 13:59:42.209092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ccc6e9e5d2'
down_revision: Union[str, None] = 'b7d3a1a34f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
