"""empty message

Revision ID: 6d1c103f7349
Revises: 49f05e23bd76
Create Date: 2024-05-27 22:07:57.184042

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d1c103f7349"
down_revision: Union[str, None] = "49f05e23bd76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("new_test_field", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "new_test_field")
    # ### end Alembic commands ###
